version: "0.5"

processes:
  frontend:
    working_dir: frontend
    command: >-
      watchexec --restart
      --watch build.sh
      --watch elm.json
      --watch src
      --watch css
      --watch public
      --debounce 1s
      -- ./build.sh

  backend:
    working_dir: backend
    command: >-
      watchexec --restart
      --watch Cargo.toml
      --watch Cargo.lock
      --watch src
      --debounce 1s
      -- cargo run
