[package]
name = "problem-bench"
description = "Coding problem benchmark workspace"
default-run = "wip"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = false
