version: "0.5"

processes:
  db:
    command: pgdb --data-dir .dev/db
    ready_log_line: "PGDB_READY:"

  web:
    command: just server
    depends_on:
      db:
        condition: process_log_ready
